### ISSUE TITLE
authorize, using: does not allow for array input

### ISSUE THREAD

**Issue by roupen** [pabloh/pathway#26]
because of this line:

https://github.com/pabloh/pathway/blob/master/lib/pathway/plugins/simple_auth.rb#L18

I'm not sure why we need a check like this so I didn't know if removing the line would cause issue. Basically I want to perform an action on multiple objects but before I do that, I want to make sure each object in the array has permission to perform the object. So it either fails all at once or processes everything. So like:

```
 process do
  step :validate
  set  :fetch_models, to: :alerts
  step :authorize, using: :alerts
  step :some_action
  set  :show_all
end
```

**Comment by pabloh** [comment]
I'll take a look but it seems like a feature we were not really using, may
be we can improve that code a bit anyway. I'll send a patch later tonight.

**Comment by pabloh** [comment]
@roupen in the meantime you can work around this by defining the block
argument with a star `|*alerts|`

**Comment by roupen** [comment]
cool thanks for the workaround Pablo!
